const DESCRIPTION = {
    '/': 'A page displaying all the routes and their descriptions',
    '/user/passkey/challenge': 'Get passkey challenge',
    '/user/passkey/register': 'Register passkey',
    '/user/passkey/login': 'Login with passkey',
    '/user/auth/login': 'Login with traditional authentication',
    '/user/auth/verify': 'Verify authentication token',
    '/user/module': 'Update which module user has enabled',
    '/user/personalization': 'Update user personalization data',
    '/projects-k/entry/get/:id': 'Get project entry details by ID',
    '/projects-k/entry/valid/:id': 'Check if project ID is valid',
    '/projects-k/entry/list': 'List project entries',
    '/projects-k/entry/create': 'Create a new project entry',
    '/projects-k/entry/update-status/:id': 'Update project entry status by ID',
    '/projects-k/progress/list-steps': 'List project progress steps',
    '/projects-k/progress/get/:id': 'Get project progress details by ID',
    '/projects-k/progress/complete-step/:id': 'Mark a project progress step as complete',
    '/projects-k/progress/uncomplete-step/:id': 'Mark a project progress step as incomplete',
    '/projects-k/files/replace/:projectId': 'Replace project files',
    '/projects-k/files/download/:projectId': 'Download project files',
    '/projects-k/files/clear-medium': 'Clear everything in the medium folder',
    '/projects-k/files/set-thumbnail/:projectId': 'Set project thumbnail',
    '/projects-k/ip': 'Get IP address of medium folder',
    '/todo-list/entry/list': 'Get list of todo entries',
    '/todo-list/entry/create': 'Create a new todo entry',
    '/todo-list/entry/update/:id': 'Update a todo entry',
    '/todo-list/entry/delete/:id': 'Delete a todo entry',
    '/todo-list/entry/toggle/:id': 'Toggle a todo entry completion status',
    '/todo-list/list/list': 'Get list of task collection lists',
    '/todo-list/list/create': 'Create a new task collection list',
    '/todo-list/tag/list': 'Get list of tags',
    '/todo-list/tag/create': 'Create a new tag',
    '/idea-box/container/get/:id': 'Get details of an idea container',
    '/idea-box/container/valid/:id': 'Check if idea container ID is valid',
    '/idea-box/container/list': 'Get list of idea containers',
    '/idea-box/container/create': 'Create a new idea container',
    '/idea-box/container/delete/:id': 'Delete an idea container',
    '/idea-box/container/update/:id': 'Update an idea container',
    '/idea-box/idea/list/:containerId': 'Get list of ideas within a container',
    '/idea-box/idea/create/:containerId': 'Create a new idea within a container',
    '/idea-box/idea/delete/:id': 'Delete an idea',
    '/idea-box/idea/update/:id': 'Update an idea',
    '/idea-box/idea/pin/:id': 'Pin an idea',
    '/idea-box/idea/archive/:id': 'Archive an idea',
    '/code-time/stats': 'Get code time statistics used by VSCode plugin',
    '/code-time/eventLog': 'Log a code time event used by VSCode plugin',
    '/code-time/activities': 'Get code time activities',
    '/code-time/statistics': 'Get code time statistics',
    '/code-time/projects': 'Get code time projects',
    '/code-time/languages': 'Get code time languages',
    '/notes/workspace/get/:id': 'Get details of a workspace',
    '/notes/workspace/valid/:id': 'Check if workspace ID is valid',
    '/notes/workspace/list': 'Get list of workspaces',
    '/notes/subject/list/:id': 'Get list of subjects within a workspace',
    '/notes/subject/create': 'Create a new subject',
    '/notes/subject/delete/:id': 'Delete a subject',
    '/notes/subject/update/:id': 'Update a subject',
    '/notes/entry/get/:id': 'Get details of a note entry',
    '/notes/entry/list/:subject/*': 'Get list of note entries within a subject (wildcard path)',
    '/notes/entry/valid/:workspace/:subject/*': 'Check if note entry path is valid',
    '/notes/entry/path/:workspace/:subject/*': 'Get path of a note entry (workspace and subject specified)',
    '/notes/entry/create/folder': 'Create a new folder for notes',
    '/notes/entry/upload/:workspace/:subject/*': 'Upload a note entry (workspace and subject specified)',
    '/notes/entry/update/folder/:id': 'Update the folder of a note entry',
    '/notes/entry/delete/:id': 'Delete a note entry',
    '/flashcards/tag/list': 'Get list of tags',
    '/flashcards/deck/get/:id': 'Get details of a deck',
    '/flashcards/deck/valid/:id': 'Check if deck ID is valid',
    '/flashcards/deck/list': 'Get list of decks',
    '/flashcards/card/list/:id': 'Get list of cards within a deck',
    '/flashcards/card/update': 'Update a flashcard (PUT)',
    '/spotify/auth/login': 'Login to Spotify for authorization',
    '/spotify/auth/callback': 'Handle Spotify authentication callback',
    '/spotify/auth/refresh': 'Refresh Spotify access token',
    '/photos/entry/name/:id': 'Get photo entry name by ID',
    '/photos/entry/download/:id': 'Download a photo entry by ID',
    '/photos/entry/bulk-download': 'Put all photos in into medium folder',
    '/photos/entry/dimensions': 'Get dimensions and other data of a photo entry',
    '/photos/entry/list': 'Get list of all photo entries',
    '/photos/entry/list/:albumId': 'Get list of photo entries within an album',
    '/photos/entry/import': 'Import photos',
    '/photos/entry/import/progress': 'Get photo import progress',
    '/photos/entry/delete': 'Delete photo entries',
    '/photos/album/get/:id': 'Get details of a photo album',
    '/photos/album/valid/:id': 'Check if photo album ID is valid',
    '/photos/album/list': 'Get list of photo albums',
    '/photos/album/create': 'Create a new photo album',
    '/photos/album/add-photos/:albumId': 'Add photos to an album',
    '/photos/album/remove-photo/:albumId': 'Remove a photo from an album',
    '/photos/album/delete/:albumId': 'Delete a photo album',
    '/photos/album/rename/:albumId': 'Rename a photo album',
    '/photos/album/set-cover/:albumId/:imageId': 'Set cover photo for an album',
    '/photos/favourites/list': 'Get list of favorite photos',
    '/photos/favourites/add-photos': 'Add photos to favorites',
    '/passwords/master/create': 'Create a master password',
    '/passwords/master/verify': 'Verify master password',
    '/passwords/password/decrypt/:id': 'Decrypt a password entry',
    '/passwords/password/list': 'Get list of password entries',
    '/passwords/password/create': 'Create a new password entry',
    '/server/disks': 'Get server disk information',
    '/server/memory': 'Get server memory information',
    '/server/cpu': 'Get server CPU information',
    '/server/info': 'Get general server information',
    '/server/cpu-temp': 'Get server CPU temperature',
    '/change-log/list': 'Get a list of change log entries',
};

export default DESCRIPTION;
